# Generated by Django 2.1.7 on 2019-03-31 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("what_does_af_stand_for", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Combination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbs_up", models.PositiveIntegerField(default=0)),
                ("thumbs_down", models.PositiveIntegerField(default=0)),
                (
                    "a_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="what_does_af_stand_for.AWord",
                    ),
                ),
                (
                    "f_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="what_does_af_stand_for.FWord",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="combination", unique_together={("a_word", "f_word")}
        ),
    ]
